### ISSUE TITLE
Missing Tokens

### ISSUE THREAD

**Issue by ISANobody** [cakeplus/mparser#2]
After doing updating opam and installing mparser.1.1, I can't import the Tokens module. Is this intended? The following works with mparser.1.0.1, but fails with opam's install of mparser.1.1:

open MParser
open MParser.Tokens

**Comment by smondet** [comment]
If you want `Tokens` you need to choose between `MParser_RE` and `MParser_PCRE` as toplevel module.

https://github.com/cakeplus/mparser/blob/master/src/mParser_RE.mli
https://github.com/cakeplus/mparser/blob/master/src/mParser_PCRE.mli

**Comment by cakeplus** [comment]
Indeed, backward compatibility is broken:

```ocaml
open MParser
```

... now needs to be replaced with ...

```ocaml
open MParser
open MParser_PCRE (* or MParser_RE *)
```

This is the price to be paid for making dependencies optional. I couldn't come up with a better design.

Don't forget to use the appropriate findlib package: either `mparser.re` or `mparser.pcre`.

Some background: https://bitbucket.org/cakeplus/mparser/issue/1/ocaml-re-compatibility.
