### ISSUE TITLE
MParser_RE breaks build in new release

### ISSUE THREAD

**Issue by baxtersa** [cakeplus/mparser#6]
I work on a project that depends on mparser, and has a travis ci set up to build against latest dependencies.

Compilation succeeds with mparser.1.2, but fails with mparser.1.2.1 with the error:

> Error: No implementations provided for the following modules:
         MParser referenced from /home/sbaxter/.opam/4.03.0/lib/mparser/lib_MParser_RE.cmxa(MParser_RE)

Any idea what causes this? My _oasis setup includes `mparser` and `mparser.re` under `BuildDepends`, with the renaming of mparser libraries do I have to modify that?

Here's a link to the travis ci output:
https://travis-ci.org/frenetic-lang/frenetic/builds/182016565

**Comment by cakeplus** [comment]
Hello, Sam. Thank you for this report.

Looking at the CI output, I see that `ocamlc` gets MParser packages in the wrong order: `-package mparser.re -package mparser`. Can you try putting `mparser` first? I guess that's the problem.

But if that's true, then why there was no such error with 1.2? I must have broken something in the OASIS setup. Very curious.

**Comment by cakeplus** [comment]
Yep, that was the problem. I've managed to reproduce it. You should put `mparser` first. Otherwise, `mparser.re` won't be able to link to it. Previously, OASIS knew about the dependency:
```
-  BuildDepends: mparser, re.perl
+  BuildDepends: re.perl
```

I had to remove it, because it caused problems on Windows (and I haven't decided yet whether to file this as a bug in OASIS, OCamlbuild, OCaml, or Cygwin).

**Comment by cakeplus** [comment]
Hold on, I'm issuing a hotfix. It was a wrong idea to drop the dependency. As for problems on Windows -- they need to be handled properly upstream (I'll file a bug somewhere).

**Comment by baxtersa** [comment]
Thanks for the assistance!

Right, as far as I can tell, when oasis resolves build dependencies and invokes `ocamlc` with a bunch of packages to link, there's some alphabetical sorting going on causing me not to be able to reorder package linking under `oasis`. Reordering did fix the issue invoking `ocamlc` manually, but I believe the right way to handle this is to tell `mparser_re` it has a dependency on `mparser`.

**Comment by cakeplus** [comment]
I've pushed the fix to OPAM (it should be available soon). Please ping here if everything goes well.

**Comment by baxtersa** [comment]
Everything passed, thanks again for working on this!
